name: 联通掌厅签到

on:
  workflow_dispatch:
  schedule:
    - cron: 30 01,* * * ?
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 联通掌厅签到
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
          
        - name: 运行时间
          run: |
            time=$(curl -s "http://quan.suning.com/getSysTime.do")
            echo -e "当前时间：\n${time}"
 
        - name: 联通掌厅签到
          env:
            user: ${{ secrets.USER }}
            appid: ${{ secrets.APPID }}
          run: |
            # 判断是否有设置appid，没有则使用默认配置
            if test -z "$appid"; then   appid="2a834d71bd261a5e0aaf6ab3342de8515ba45a2f4c0e8712e65957be1e9474a0c576691c61483b30267034962b8704022e1c19ceb47ca212353169ff237ba9e86da8ab1000af550cd08cf5048ee608e4"; fi
            
            for u in $user
            do
              bash CnUnicom.sh ${u/,/ }
            done

